const appname = "eMart";
const appversion = "Version 1.0.0";
const credits = "@IH SolutionS";
const email = "Email";
const emailHint = "abc@gmail.com";
const password = "Password";
const passwordHint = "*******";
const retypePasswod = "Retype Password";
const name = "Name";
const nameHint = "IH Sohag";
const forgetPassword = "Forget Password";
const login = "Log in";
const signup = "Sign up";
const createNewAccount = "or, create a new account";
const loginWith = "Log in with";
const privacyPolicy = "Privacy Policy";
const termsAndCondition = "Terms and Condition";
const alreadyHaveAccount = "Already have an account? ";
//home strings
const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account";
//home screen strings
const searchAnything = "Search anything...",
    todayDeal = "Today's Deal",
    flashSell = "Flash Sell",
    brand = "Brand";
const topSeller = "Top Sellers",
    topCategories = "Top Categories",
    featuredCategories = "Featured Categories",
    womenDresses = "Women Dresses",
    girlsWatches = "GirlsWatches",
    mobilePhone = "Mobile Phone",
    boysGlasses = "Boys Glasses",
    tShirts = "T-shirts",
    girlsDresses = "Girls Dresses",
    featuredProduct = "Featured Product";

//categories screen strings
const womenClothing = "Women Clothing",
    menClothingFashion = "Men Clothing & Fashion",
    computerAccessories = "Computer & Accessories",
    automobile = "Automobile",
    kidsToys = "Kids & Toys",
    sports = "Sports",
    jewelery = "Jewelery",
    cellphone = "Cellphone & Tab",
    furniture = "Furniture";
